version: "3"

services:
  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  selenium:
    image: seleniarm/node-chromium:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    restart: always
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=0
      - SE_NODE_MAX_SESSIONS=12
    # deploy:
    #   mode: replicated
    #   replicas: 6

  scrapp:
    image: scrapp:latest
    restart: always
    ports:
      - "8899:8888"
    environment:
      - REMOTE_SELENIUM=http://selenium-hub:4444/wd/hub
